### ISSUE TITLE
User can join or host game [PBL #36]

### ISSUE THREAD

**Issue by JevonJ** [JevonJ/Stocky#1]
- [x] Design Welcome Page
- [x] Design Join(Game List) Page
- [x] Design Host create Page
- [x] Design lobby Page
- [x] Implement Welcome Page
- [x] Implement Join(Game List) Page
- [x] Implement Host create Page
- [x] Implement lobby Page
- [x] Connect Interfaces(screen flow)
- [x] Add functionality for hosting and connect to interface 
- [x] Add functionality for joining **without** password and connect to interface
- [x] Add functionality for joining **with** password and connect to interface
- [x] Add functionality to start the game after joining or registering(Only the host can start the game).

**Comment by JevonJ** [comment]
![whatsapp image 2018-05-27 at 10 40 09 pm](https://user-images.githubusercontent.com/19817313/40588700-2eb7417e-61ff-11e8-84fa-d52ec359676f.jpeg)

**Comment by samadhi8993** [comment]
![welcome_2](https://user-images.githubusercontent.com/39255323/40663828-318f0016-6377-11e8-9120-72089a680f17.jpg)

**Comment by samadhi8993** [comment]
![signup](https://user-images.githubusercontent.com/39255323/40697525-3c8707ea-63e8-11e8-8e2e-e199cc32a1d0.jpg)

**Comment by samadhi8993** [comment]
![login](https://user-images.githubusercontent.com/39255323/40697535-45a5ce56-63e8-11e8-93b1-ce0d87bc402d.jpg)

**Comment by samadhi8993** [comment]
![join](https://user-images.githubusercontent.com/39255323/40697543-4d1d4e98-63e8-11e8-9033-baf1f4cc9bae.jpg)

**Comment by samadhi8993** [comment]
![lobby](https://user-images.githubusercontent.com/39255323/40699920-b2f23376-63f4-11e8-915c-cdf548f4aa7e.jpg)

**Comment by AshaneAlvis** [comment]
Hi team mates, I have committed the Signup page. @JevonJ can check and review it.
