### ISSUE TITLE
User can play with online players [PBL #3]

### ISSUE THREAD

**Issue by JevonJ** [JevonJ/Stocky#3]
- [x] Research best way for a client-server game
- [x] Implement solution

**Comment by JevonJ** [comment]
Current Technologies in consideration are Express.js and socket.io based backend or a php based backend.

**Comment by JevonJ** [comment]
And Reactjs for the front end.

**Comment by tharaniya1992** [comment]
according to my research Js best way for a client-server game because JS is faster than php
